"""Initial history + calibration tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-03

Creates estimate_history, phase_history, and calibration_aggregates plus the
indexes the twin calibration queries rely on. Mirrors db/orm_models.py exactly —
hand-written rather than autogenerated so the migration is reviewable.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "estimate_history",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("project_name", sa.String(length=255), nullable=False, server_default=""),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("raw_input", sa.Text, nullable=False, server_default=""),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("project_type", sa.String(length=64), nullable=True),
        sa.Column("engagement_model", sa.String(length=32), nullable=True),
        sa.Column("target_timeline_weeks", sa.Integer, nullable=True),
        sa.Column("total_ai_assisted_mid_hours", sa.Float, nullable=True),
        sa.Column("total_manual_only_mid_hours", sa.Float, nullable=True),
        sa.Column("ai_hours_saved", sa.Float, nullable=True),
        sa.Column("ai_cost_saved_usd", sa.Float, nullable=True),
        sa.Column("total_cost_ai_assisted_usd", sa.Float, nullable=True),
        sa.Column("total_cost_manual_only_usd", sa.Float, nullable=True),
        sa.Column("confidence", sa.Float, nullable=True),
        sa.Column("duration_weeks_low", sa.Float, nullable=True),
        sa.Column("duration_weeks_high", sa.Float, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_estimate_history_status", "estimate_history", ["status"])
    op.create_index("ix_estimate_history_industry", "estimate_history", ["industry"])
    op.create_index("ix_estimate_history_project_type", "estimate_history", ["project_type"])
    op.create_index("ix_estimate_history_created_at", "estimate_history", ["created_at"])

    op.create_table(
        "phase_history",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "estimate_id",
            sa.String(length=36),
            sa.ForeignKey("estimate_history.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("twin_name", sa.String(length=64), nullable=False),
        sa.Column("algorithm", sa.String(length=64), nullable=False),
        sa.Column("ai_assisted_optimistic", sa.Float, nullable=False, server_default="0"),
        sa.Column("ai_assisted_mid", sa.Float, nullable=False, server_default="0"),
        sa.Column("ai_assisted_pessimistic", sa.Float, nullable=False, server_default="0"),
        sa.Column("manual_only_optimistic", sa.Float, nullable=False, server_default="0"),
        sa.Column("manual_only_mid", sa.Float, nullable=False, server_default="0"),
        sa.Column("manual_only_pessimistic", sa.Float, nullable=False, server_default="0"),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0"),
        sa.Column("maturity_level", sa.Integer, nullable=True),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("project_type", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_phase_history_estimate_id", "phase_history", ["estimate_id"])
    op.create_index("ix_phase_history_phase", "phase_history", ["phase"])
    op.create_index("ix_phase_history_maturity_level", "phase_history", ["maturity_level"])
    op.create_index("ix_phase_history_industry", "phase_history", ["industry"])
    op.create_index("ix_phase_history_project_type", "phase_history", ["project_type"])
    # Composite for the calibration aggregation query.
    op.create_index(
        "ix_phase_history_calibration_lookup",
        "phase_history",
        ["phase", "industry", "project_type", "maturity_level"],
    )

    op.create_table(
        "calibration_aggregates",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("industry", sa.String(length=64), nullable=False, server_default=""),
        sa.Column("project_type", sa.String(length=64), nullable=False, server_default=""),
        sa.Column("maturity_level", sa.Integer, nullable=False, server_default="0"),
        sa.Column("sample_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("avg_ai_assisted_mid", sa.Float, nullable=False, server_default="0"),
        sa.Column("avg_manual_only_mid", sa.Float, nullable=False, server_default="0"),
        sa.Column("avg_confidence", sa.Float, nullable=False, server_default="0"),
        sa.Column("avg_ai_reduction_pct", sa.Float, nullable=False, server_default="0"),
        sa.Column(
            "last_refreshed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "phase",
            "industry",
            "project_type",
            "maturity_level",
            name="uq_calibration_dimensions",
        ),
    )
    op.create_index("ix_calibration_aggregates_phase", "calibration_aggregates", ["phase"])
    op.create_index("ix_calibration_aggregates_industry", "calibration_aggregates", ["industry"])
    op.create_index(
        "ix_calibration_aggregates_project_type",
        "calibration_aggregates",
        ["project_type"],
    )
    op.create_index(
        "ix_calibration_aggregates_maturity_level",
        "calibration_aggregates",
        ["maturity_level"],
    )


def downgrade() -> None:
    op.drop_table("calibration_aggregates")
    op.drop_table("phase_history")
    op.drop_table("estimate_history")
